### PR TITLE
Fix Upload File Issue

### PR DESCRIPTION
**Pull request by mhanzla80**
**This is how we can add the picture to the question model in the form of base64Encode String**
```dart

void fileUpload(ValueChanged<String> callback) async {
    /// Select File image the camera and Encode it to the base64Encode then
    /// pass it to the callback and package will handle by itself.

    final picker = ImagePicker();
    // Pick an image
    final image = await picker.pickImage(source: ImageSource.camera);
    if (image != null) {
      final imageBytes = await image.readAsBytes();
      final base64File = base64Encode(imageBytes);
      callback.call(base64File);
    }
  }
```

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
This change only allows to pick image. thus limiting the possibilities of uploading files and other things. what you can do is a function so that the user can add their own function for the upload

**Comment by mhanzla80** [comment]
So do i have to move the implementations inside the `FormWidget()` by adding a dialog which ask user to choose select file from camera or storage ?
Do you have any suggestions ?

**Comment by tanmoy27112000** [comment]
exactly.

**Comment by mhanzla80** [comment]
Okay I am going to implement it like this.
And is it okay to encode file in base64 String ?

**Comment by tanmoy27112000** [comment]
No return it as it is

**Comment by mhanzla80** [comment]
> No return it as it is

okay

**Comment by mhanzla80** [comment]
Hey @tanmoy27112000, I am going to use [file_picker: ^5.2.2](https://pub.dev/packages/file_picker) this package for file upload functionality. Is it okay ? Can i use it ?

**Comment by tanmoy27112000** [comment]
use multi picker that will add multi pick option . that will be good

**Comment by mhanzla80** [comment]
> use multi picker that will add multi pick option . that will be good

you mean i use the multi picker functionality of this [file_picker: ^5.2.2](https://pub.dev/packages/file_picker) package ?

**Comment by tanmoy27112000** [comment]
yes

**Comment by mhanzla80** [comment]
Hey @tanmoy27112000, I have updated it with multiple file.
Can you review it ?

**Comment by mhanzla80** [comment]
Don't you think we have to encode the files in base64 String because we are changing the type of answer to string ?

**Comment by tanmoy27112000** [comment]
save the path in the answer key as list of string

**Comment by mhanzla80** [comment]
> save the path in the answer key as list of string

yes i did this the same but there is nothing uploaded to the server just path string.
How can i fix this ?

WhatsApp Image 2022-10-26 at 9 57 57 PM

**Comment by mhanzla80** [comment]
I've tried it by Encoding the file to base64 String and it worked.
So, I think it's better to do it by saving the file into base64 encoded string in answer key.
@tanmoy27112000 can you check it ?

**Comment by mhanzla80** [comment]
@tanmoy27112000 I will not merge it until it works well.

**Comment by tanmoy27112000** [comment]
This package does not upload directly to any server . once the user clicks on submit he we get all the data and then they can easily use the path to get the file and upload it accordingly.

**Comment by mhanzla80** [comment]
> > save the path in the answer key as list of string
> 
> yes i did this the same but there is nothing uploaded to the server just path string. How can i fix this ?
> 
> WhatsApp Image 2022-10-26 at 9 57 57 PM

yes i've tried to upload data on submit but get error in parsing file path.

**Comment by mhanzla80** [comment]
i am trying to upload data provided by onSubmit callback and getting this error.
And also can you tell me how can we upload data from the path ?

**Comment by mhanzla80** [comment]
@tanmoy27112000 I have resolved all the conflicts can you merge it now so i can continue my work ?

**Comment by tanmoy27112000** [comment]
done. Thanks for your contribution! @mhanzla80 . I will publish the new build in few minutes

**Comment by mhanzla80** [comment]
Thanks @tanmoy27112000 for your cooperations.

**Pull request merged**
