### PR TITLE
Set state to provider

### PR DESCRIPTION
**Pull request by thecre8tor**

### CODE REVIEW

**Comment by thecre8tor** [comment]
Hi Tanmoy,
I have completed the `Set state to provider #25` issue and I also refactored the package architecture.
Do well to review and test.
I will be expecting to hear from you soonest.

**Comment by tanmoy27112000** [comment]
Looks great. Thanks for contributing with this issue. If you have any ideas how to improve this package please inform me.

**Comment by thecre8tor** [comment]
Yeah, sure. 
I am going to reach out to you when I have an idea.

**Comment by thecre8tor** [comment]
Can you close the issue?
I realize the issue is still open.

**Pull request merged**
